"""add_barberbook24_staff_fields

Revision ID: 44948f767440
Revises: 81edbba7ae59
Create Date: 2026-02-07 19:04:04.367590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44948f767440'
down_revision: Union[str, Sequence[str], None] = '81edbba7ae59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('isPaidConfirmation', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('expiresAt', sa.DateTime(), nullable=True))
    op.add_column('staff_profiles', sa.Column('workingDays', sa.JSON(), nullable=True))
    op.add_column('staff_profiles', sa.Column('workingHours', sa.JSON(), nullable=True))
    op.add_column('staff_profiles', sa.Column('bufferTime', sa.Integer(), nullable=True))
    op.add_column('staff_profiles', sa.Column('isAvailable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_profiles', 'isAvailable')
    op.drop_column('staff_profiles', 'bufferTime')
    op.drop_column('staff_profiles', 'workingHours')
    op.drop_column('staff_profiles', 'workingDays')
    op.drop_column('bookings', 'expiresAt')
    op.drop_column('bookings', 'isPaidConfirmation')
    # ### end Alembic commands ###
