"""Add owner supervision models: enhanced audit log, owner settings, and staff reliability

Revision ID: 4c38ba059a71
Revises: a2d5c2783c50
Create Date: 2026-02-07 20:55:02.638245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c38ba059a71'
down_revision: Union[str, Sequence[str], None] = 'a2d5c2783c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('audit_logs', sa.Column('actorId', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('actorRole', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('actionType', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('shopId', sa.String(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'shops', ['shopId'], ['id'])
    op.drop_column('audit_logs', 'newValue')
    op.drop_column('audit_logs', 'oldValue')
    op.drop_column('audit_logs', 'userId')
    op.drop_column('audit_logs', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('oldValue', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('newValue', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'shopId')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'actionType')
    op.drop_column('audit_logs', 'actorRole')
    op.drop_column('audit_logs', 'actorId')
    op.drop_column('audit_logs', 'timestamp')
    # ### end Alembic commands ###
