"""Add AuditLog table

Revision ID: 5bb93e83d0a6
Revises: 44948f767440
Create Date: 2026-02-07 19:32:48.623357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb93e83d0a6'
down_revision: Union[str, Sequence[str], None] = '44948f767440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entityType', sa.String(), nullable=False),
    sa.Column('entityId', sa.String(), nullable=False),
    sa.Column('oldValue', sa.JSON(), nullable=True),
    sa.Column('newValue', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
