"""Add reminder flags to Booking

Revision ID: a2d5c2783c50
Revises: cbd373ebf310
Create Date: 2026-02-07 19:41:14.957870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d5c2783c50'
down_revision: Union[str, Sequence[str], None] = 'cbd373ebf310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminded24h', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('reminded2h', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('reminded15m', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminded15m')
    op.drop_column('bookings', 'reminded2h')
    op.drop_column('bookings', 'reminded24h')
    # ### end Alembic commands ###
