"""Add idempotencyKey to Booking

Revision ID: cbd373ebf310
Revises: 5bb93e83d0a6
Create Date: 2026-02-07 19:33:45.558120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd373ebf310'
down_revision: Union[str, Sequence[str], None] = '5bb93e83d0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('idempotencyKey', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'bookings', ['idempotencyKey'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_column('bookings', 'idempotencyKey')
    # ### end Alembic commands ###
