"""Initial Schema Fix

Revision ID: d4eb1edab2b7
Revises: 
Create Date: 2026-02-05 05:25:27.253907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4eb1edab2b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('profilePhoto', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('portfolio', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('isRead', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviewsCount', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('ownerId', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shopId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shopId'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shopId', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shopId'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('shopId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviewsCount', sa.Integer(), nullable=True),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shopId'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customerId', sa.String(), nullable=True),
    sa.Column('shopId', sa.String(), nullable=True),
    sa.Column('staffId', sa.String(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('timeSlot', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('totalAmount', sa.Float(), nullable=False),
    sa.Column('totalDuration', sa.Integer(), nullable=True),
    sa.Column('bookedAt', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shopId'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staffId'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shopId', sa.String(), nullable=True),
    sa.Column('staffId', sa.String(), nullable=True),
    sa.Column('customerId', sa.String(), nullable=True),
    sa.Column('customerName', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('helpful', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shopId'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staffId'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_services_link',
    sa.Column('staffId', sa.String(), nullable=False),
    sa.Column('serviceId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['serviceId'], ['services.id'], ),
    sa.ForeignKeyConstraint(['staffId'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('staffId', 'serviceId')
    )
    op.create_table('staff_work_photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('staffId', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['staffId'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_work_photos')
    op.drop_table('staff_services_link')
    op.drop_table('reviews')
    op.drop_table('bookings')
    op.drop_table('staff_profiles')
    op.drop_table('shop_photos')
    op.drop_table('services')
    op.drop_table('shops')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
