"""add_fcm_token_to_user

Revision ID: d9f5771ee76d
Revises: 4c38ba059a71
Create Date: 2026-02-08 15:05:35.779651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f5771ee76d'
down_revision: Union[str, Sequence[str], None] = '4c38ba059a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcmToken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcmToken')
    # ### end Alembic commands ###
