"""production_hardening_time_safety

Revision ID: f4ccbb4037f4
Revises: 3c4182e3dadb
Create Date: 2026-02-13 11:45:10.750040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ccbb4037f4'
down_revision: Union[str, Sequence[str], None] = '3c4182e3dadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.add_column('bookings', sa.Column('startTime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('endTime', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_bookings_endTime'), 'bookings', ['endTime'], unique=False)
    op.create_index('ix_bookings_staff_range_status', 'bookings', ['staffId', 'startTime', 'endTime', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_startTime'), 'bookings', ['startTime'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    
    # PostgreSQL Exclusion Constraint for Time Overlap
    op.create_exclude_constraint(
        'uq_staff_time_overlap',
        'bookings',
        ('staffId', '='),
        (sa.func.tstzrange(sa.column('startTime'), sa.column('endTime')), '&&'),
        where="status IN ('CONFIRMED', 'AWAITING_CUSTOMER_CONFIRMATION')"
    )

    op.alter_column('user_roles', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'agreed_to_privacy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'agreed_to_terms',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'agreed_to_terms',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'agreed_to_privacy',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_roles', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_startTime'), table_name='bookings')
    op.drop_index('ix_bookings_staff_range_status', table_name='bookings')
    op.drop_index(op.f('ix_bookings_endTime'), table_name='bookings')
    op.drop_column('bookings', 'endTime')
    op.drop_column('bookings', 'startTime')
    # ### end Alembic commands ###
